/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Content
 */
export interface Content {
    /**
     * 
     * @type {number}
     * @memberof Content
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    'resumen'?: string;
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    'font'?: string;
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    'link'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Content
     */
    'futureJob'?: boolean;
}

